server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  server:
    renewal-threshold-update-interval-ms: 1000
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
